#!/bin/bash

if [[ "${UID}" -ne 0 ]]
then
echo "Please run with sudo or as root"
exit 1
fi
if [[ "${#}" -lt 1 ]]
then
echo "Please enter the name for USER_NAME and COMMENT fields"
exit 1
fi
USER_NAME="${1}"
shift
COMMENT="${@}"

PASSWORD=$(date +%s%N | sha256sum | head -c11)
useradd -c "${COMMENT}" -m ${USER_NAME}
if [[ "${?}" -ne 0 ]]
then
echo "${USER_NAME} cannot be created"
exit 1
fi
echo ${PASSWORD} | passwd --stdin ${USER_NAME}
if [[ "${?}" -ne 0 ]]
then
echo "The password could not be set"
exit 1
fi
passwd -e ${USER_NAME}
echo
echo "username: ${USER_NAME}"
echo
echo "full name: ${COMMENT}"
echo
echo "your new password is: ${PASSWORD}"
echo
echo "host: ${HOSTNAME}"
exit 0
